# MySQL. Versions 5.5.8 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem "mysql2"
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  password: "Uso914943@"
  host: localhost
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: furima_42612_development

test:
  <<: *default
  database: furima_42612_test

production:
  <<: *default
  database: furima_42612_production
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>